/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSearchesRouteImport } from './routes/dashboard.searches'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminCarsRouteImport } from './routes/admin.cars'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSearchesRoute = DashboardSearchesRouteImport.update({
  id: '/searches',
  path: '/searches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarsRoute = AdminCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AdminRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/cars'
    | '/admin/users'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/searches'
    | '/admin/'
    | '/dashboard/'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/cars'
    | '/admin/users'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/searches'
    | '/admin'
    | '/dashboard'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/cars'
    | '/admin/users'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/searches'
    | '/admin/'
    | '/dashboard/'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/searches': {
      id: '/dashboard/searches'
      path: '/searches'
      fullPath: '/dashboard/searches'
      preLoaderRoute: typeof DashboardSearchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars': {
      id: '/admin/cars'
      path: '/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminCarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCarsRoute: typeof AdminCarsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCarsRoute: AdminCarsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSearchesRoute: typeof DashboardSearchesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSearchesRoute: DashboardSearchesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
